export const PRODUCTS = [{
  isSelected: false,
  productId: '1234',
  origin: 'China',
  productType: 'cat food',
  name: 'Cat Food by Larry',
  price: 10.99,
},
{
  isSelected: false,
  productId: '2345',
  origin: 'USA',
  productType: 'cat food',
  name: 'Alfie Chow',
  price: 16.99,
},
{
  isSelected: false,
  productId: '456',
  origin: 'USA',
  productType: 'cat food',
  name: 'For Cats Not Dogs Food',
  price: 15.99,
},
{
  isSelected: false,
  productId: '664',
  origin: 'USA',
  productType: 'dog food',
  name: 'Dog Food by Larry',
  price: 24.99,
},
{
  isSelected: false,
  productId: '786',
  origin: 'USA',
  productType: 'dog food',
  name: 'Punky Pete\'s Puppy Yum Yums',
  price: 28.99,
},
{
  isSelected: false,
  productId: '984359346',
  origin: 'China',
  productType: 'cat toy',
  name: 'Dead Mouse',
  price: 4.99,
},
{
  isSelected: false,
  productId: '78976',
  origin: 'EU',
  productType: 'bird food',
  name: 'Sunflowers and Sassafrass',
  price: 18.99,
},
{
  isSelected: false,
  productId: '7667856',
  origin: 'Canada',
  productType: 'people food',
  name: 'NOT Dog Food',
  price: 31.99,
},
{
  isSelected: false,
  productId: '7682354',
  origin: 'Brazil',
  productType: 'bird food',
  name: 'Polly Wants to Eat Me',
  price: 10.99,
},
{
  isSelected: false,
  productId: '4356345345',
  origin: 'Canada',
  productType: 'bird food',
  name: 'Super Seedy',
  price: 19.99,
},
{
  isSelected: false,
  productId: '45745745',
  origin: 'EU',
  productType: 'cat toy',
  name: 'Tickle Monkey',
  price: 8.99,
},
{
  isSelected: false,
  productId: '672',
  origin: 'Brazil',
  productType: 'dog toy',
  name: 'Bizzy Bee',
  price: 5.99,
}];

export const PRODUCT_TYPE_FILTERS = ['cat food', 'dog food', 'bird food', 'people food', 'cat toy', 'dog toy'];
